import { ProcurementRequest } from './db';

export const generateMockRequests = (): ProcurementRequest[] => {
  return [
    {
      id: '1',
      title: 'Laboratory Equipment Purchase',
      department: 'Computer Science',
      course: 'UG',
      category: 'Equipment',
      orderType: '>25000',
      description: 'Purchase of new laboratory computers and networking equipment for the expanded computer lab.',
      justification: 'Current equipment is outdated and cannot support modern software development tools required for the updated curriculum.',
      items: [
        { id: '1-1', itemName: 'Desktop Computer (i7, 16GB RAM)', quantity: 15, approxAmount: 60000 },
        { id: '1-2', itemName: 'Network Switch (24-port)', quantity: 2, approxAmount: 15000 },
        { id: '1-3', itemName: 'UPS (1KVA)', quantity: 15, approxAmount: 22500 },
      ],
      totalAmount: 97500,
      documents: [],
      status: 'pending',
      createdBy: 'Dr. Rajesh Kumar',
      createdByRole: 'faculty',
      createdAt: Date.now() - 86400000 * 2,
      updatedAt: Date.now() - 86400000 * 2,
      comments: [],
      approvals: {},
    },
    {
      id: '2',
      title: 'Chemistry Lab Chemicals',
      department: 'Chemistry',
      course: 'PG',
      category: 'Consumables',
      orderType: '<25000',
      description: 'Essential chemicals and reagents for research and practical sessions.',
      justification: 'Required for ongoing research projects and student practical examinations.',
      items: [
        { id: '2-1', itemName: 'Sodium Hydroxide (500g)', quantity: 5, approxAmount: 2500 },
        { id: '2-2', itemName: 'Hydrochloric Acid (1L)', quantity: 10, approxAmount: 3000 },
        { id: '2-3', itemName: 'Lab Glassware Set', quantity: 3, approxAmount: 9000 },
      ],
      totalAmount: 14500,
      documents: [],
      status: 'approved_hod',
      createdBy: 'Prof. Anita Sharma',
      createdByRole: 'faculty',
      createdAt: Date.now() - 86400000 * 5,
      updatedAt: Date.now() - 86400000 * 3,
      comments: [
        {
          id: 'c1',
          userId: 'hod1',
          userName: 'Dr. Suresh Patel',
          userRole: 'HOD',
          comment: 'Approved. Please ensure proper storage facilities.',
          timestamp: Date.now() - 86400000 * 3,
        },
      ],
      approvals: {
        hod: { approved: true, timestamp: Date.now() - 86400000 * 3, userId: 'hod1', userName: 'Dr. Suresh Patel' },
      },
    },
    {
      id: '3',
      title: 'Library Book Acquisition',
      department: 'Library',
      course: 'UG',
      category: 'Books',
      orderType: '>100000',
      description: 'Purchase of textbooks and reference materials for the new academic year.',
      justification: 'Expanding library collection to support new courses and increased student enrollment.',
      items: [
        { id: '3-1', itemName: 'Engineering Textbooks (Various)', quantity: 200, approxAmount: 80000 },
        { id: '3-2', itemName: 'Science Reference Books', quantity: 100, approxAmount: 40000 },
        { id: '3-3', itemName: 'Digital Library Subscription', quantity: 1, approxAmount: 25000 },
      ],
      totalAmount: 145000,
      documents: [],
      status: 'approved_principal',
      createdBy: 'Ms. Priya Desai',
      createdByRole: 'faculty',
      createdAt: Date.now() - 86400000 * 10,
      updatedAt: Date.now() - 86400000 * 1,
      comments: [
        {
          id: 'c2',
          userId: 'hod2',
          userName: 'Dr. Amit Singh',
          userRole: 'HOD',
          comment: 'Essential for academic excellence. Approved.',
          timestamp: Date.now() - 86400000 * 8,
        },
        {
          id: 'c3',
          userId: 'principal1',
          userName: 'Dr. Meera Iyer',
          userRole: 'Principal',
          comment: 'Approved. Coordinate with purchase officer for procurement.',
          timestamp: Date.now() - 86400000 * 1,
        },
      ],
      approvals: {
        hod: { approved: true, timestamp: Date.now() - 86400000 * 8, userId: 'hod2', userName: 'Dr. Amit Singh' },
        principal: { approved: true, timestamp: Date.now() - 86400000 * 1, userId: 'principal1', userName: 'Dr. Meera Iyer' },
      },
    },
  ];
};
