import { ProcurementRequest } from './newDb';

export const generateMockRequests = (): ProcurementRequest[] => {
  const now = Date.now();
  
  return [
    {
      id: '1',
      title: 'Laboratory Equipment Purchase for Computer Lab',
      department: 'Computer Science',
      course: 'UG',
      category: 'Equipment',
      orderType: '>25000',
      description: 'Purchase of new laboratory computers and networking equipment for the expanded computer lab to support modern software development and cloud computing courses.',
      justification: 'Current equipment is outdated (8+ years old) and cannot support modern software development tools, IDEs, and virtualization required for the updated curriculum. This upgrade is essential for maintaining educational quality.',
      items: [
        { id: '1-1', itemName: 'Desktop Computer (i7, 16GB RAM, 512GB SSD)', quantity: 15, approxAmount: 60000 },
        { id: '1-2', itemName: 'Network Switch (24-port Gigabit)', quantity: 2, approxAmount: 15000 },
        { id: '1-3', itemName: 'UPS (1KVA)', quantity: 15, approxAmount: 22500 },
      ],
      totalAmount: 97500,
      documents: [],
      currentStep: 'hod_1',
      createdBy: 'Dr. Rajesh Kumar',
      createdByRole: 'faculty',
      createdAt: now - 86400000 * 2,
      updatedAt: now - 86400000 * 2,
      comments: [],
      workflowHistory: [],
    },
    {
      id: '2',
      title: 'Chemistry Lab Consumables and Reagents',
      department: 'Chemistry',
      course: 'PG',
      category: 'Consumables',
      orderType: '<25000',
      description: 'Essential chemicals, reagents, and glassware for ongoing research projects and practical sessions for PG students.',
      justification: 'Required for ongoing research projects and student practical examinations scheduled for next month. Current stock is depleted.',
      items: [
        { id: '2-1', itemName: 'Sodium Hydroxide (500g)', quantity: 5, approxAmount: 2500 },
        { id: '2-2', itemName: 'Hydrochloric Acid (1L)', quantity: 10, approxAmount: 3000 },
        { id: '2-3', itemName: 'Lab Glassware Set', quantity: 3, approxAmount: 9000 },
        { id: '2-4', itemName: 'Safety Equipment (Goggles, Gloves)', quantity: 20, approxAmount: 4500 },
      ],
      totalAmount: 19000,
      documents: [],
      currentStep: 'so_1',
      createdBy: 'Prof. Anita Sharma',
      createdByRole: 'faculty',
      createdAt: now - 86400000 * 5,
      updatedAt: now - 86400000 * 3,
      comments: [
        {
          id: 'c1',
          userId: 'hod1',
          userName: 'Dr. Suresh Patel',
          userRole: 'HOD',
          comment: 'Approved. Please ensure proper storage facilities are available. Also verify safety compliance.',
          timestamp: now - 86400000 * 3,
          action: 'approve',
          step: 'hod_1',
        },
      ],
      workflowHistory: [
        {
          step: 'hod_1',
          userId: 'hod1',
          userName: 'Dr. Suresh Patel',
          userRole: 'hod',
          action: 'approve',
          comment: 'Approved. Please ensure proper storage facilities are available.',
          timestamp: now - 86400000 * 3,
        },
      ],
    },
    {
      id: '3',
      title: 'Library Digital Resources Subscription',
      department: 'Library',
      course: 'UG',
      category: 'Digital Resources',
      orderType: '>100000',
      description: 'Annual subscription to IEEE Xplore, Springer, and other digital libraries for engineering and science departments.',
      justification: 'Expanding library collection to support new courses and increased student enrollment. Digital resources are essential for research and project work.',
      items: [
        { id: '3-1', itemName: 'IEEE Xplore Digital Library (Annual)', quantity: 1, approxAmount: 45000 },
        { id: '3-2', itemName: 'Springer Journal Access', quantity: 1, approxAmount: 35000 },
        { id: '3-3', itemName: 'ACM Digital Library', quantity: 1, approxAmount: 30000 },
        { id: '3-4', itemName: 'JSTOR Access', quantity: 1, approxAmount: 25000 },
      ],
      totalAmount: 135000,
      documents: [],
      currentStep: 'principal_1',
      createdBy: 'Ms. Priya Desai',
      createdByRole: 'faculty',
      createdAt: now - 86400000 * 10,
      updatedAt: now - 86400000 * 1,
      comments: [
        {
          id: 'c2',
          userId: 'hod2',
          userName: 'Dr. Amit Singh',
          userRole: 'HOD',
          comment: 'Essential for academic excellence. Highly recommended.',
          timestamp: now - 86400000 * 8,
          action: 'approve',
          step: 'hod_1',
        },
        {
          id: 'c3',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'Store Officer',
          comment: 'Digital resources verified. All subscriptions are valid and necessary.',
          timestamp: now - 86400000 * 6,
          action: 'approve',
          step: 'so_1',
        },
        {
          id: 'c4',
          userId: 'po1',
          userName: 'Mrs. Lakshmi Iyer',
          userRole: 'Purchase Officer',
          comment: 'Quotations obtained from authorized vendors. Pricing is competitive.',
          timestamp: now - 86400000 * 4,
          action: 'approve',
          step: 'po_1',
        },
      ],
      workflowHistory: [
        {
          step: 'hod_1',
          userId: 'hod2',
          userName: 'Dr. Amit Singh',
          userRole: 'hod',
          action: 'approve',
          comment: 'Essential for academic excellence.',
          timestamp: now - 86400000 * 8,
        },
        {
          step: 'so_1',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'so',
          action: 'approve',
          comment: 'Digital resources verified.',
          timestamp: now - 86400000 * 6,
        },
        {
          step: 'po_1',
          userId: 'po1',
          userName: 'Mrs. Lakshmi Iyer',
          userRole: 'po',
          action: 'approve',
          comment: 'Quotations obtained from authorized vendors.',
          timestamp: now - 86400000 * 4,
        },
      ],
    },
    {
      id: '4',
      title: 'Furniture for New Classrooms',
      department: 'Administration',
      course: 'UG',
      category: 'Furniture',
      orderType: '>100000',
      description: 'Student desks, chairs, and faculty tables for 3 new classrooms being set up in the new building.',
      justification: 'New building construction completed. Furniture required before next semester begins in 2 months.',
      items: [
        { id: '4-1', itemName: 'Student Desk & Chair Set', quantity: 150, approxAmount: 90000 },
        { id: '4-2', itemName: 'Faculty Table & Chair', quantity: 6, approxAmount: 24000 },
        { id: '4-3', itemName: 'Whiteboard (8ft x 4ft)', quantity: 6, approxAmount: 18000 },
        { id: '4-4', itemName: 'Notice Boards', quantity: 6, approxAmount: 6000 },
      ],
      totalAmount: 138000,
      documents: [],
      currentStep: 'payment_officer',
      createdBy: 'Mr. Vijay Kumar',
      createdByRole: 'faculty',
      createdAt: now - 86400000 * 15,
      updatedAt: now - 86400000 * 2,
      comments: [
        {
          id: 'c5',
          userId: 'principal1',
          userName: 'Dr. Meera Iyer',
          userRole: 'Principal',
          comment: 'Approved. Essential for upcoming semester. Coordinate with civil department for delivery schedule.',
          timestamp: now - 86400000 * 2,
          action: 'approve',
          step: 'principal_1',
        },
      ],
      workflowHistory: [
        {
          step: 'hod_1',
          userId: 'admin1',
          userName: 'Mr. Anil Kapoor',
          userRole: 'admin',
          action: 'approve',
          timestamp: now - 86400000 * 13,
        },
        {
          step: 'so_1',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'so',
          action: 'approve',
          timestamp: now - 86400000 * 11,
        },
        {
          step: 'po_1',
          userId: 'po1',
          userName: 'Mrs. Lakshmi Iyer',
          userRole: 'po',
          action: 'approve',
          timestamp: now - 86400000 * 9,
        },
        {
          step: 'principal_1',
          userId: 'principal1',
          userName: 'Dr. Meera Iyer',
          userRole: 'principal',
          action: 'approve',
          comment: 'Approved. Essential for upcoming semester.',
          timestamp: now - 86400000 * 2,
        },
      ],
    },
    {
      id: '5',
      title: 'Sports Equipment for Annual Day',
      department: 'Physical Education',
      course: 'UG',
      category: 'Sports Equipment',
      orderType: '<25000',
      description: 'Various sports equipment including cricket bats, footballs, and athletics gear for the upcoming annual sports day.',
      justification: 'Annual sports day scheduled in 6 weeks. Current equipment is worn out and insufficient for all participants.',
      items: [
        { id: '5-1', itemName: 'Cricket Bat (Professional)', quantity: 10, approxAmount: 8000 },
        { id: '5-2', itemName: 'Football (Size 5)', quantity: 15, approxAmount: 6000 },
        { id: '5-3', itemName: 'Athletics Equipment Set', quantity: 2, approxAmount: 7500 },
      ],
      totalAmount: 21500,
      documents: [],
      currentStep: 'completed',
      createdBy: 'Coach Arjun Reddy',
      createdByRole: 'faculty',
      createdAt: now - 86400000 * 30,
      updatedAt: now - 86400000 * 1,
      comments: [],
      workflowHistory: [
        {
          step: 'hod_1',
          userId: 'hod3',
          userName: 'Dr. Sports HOD',
          userRole: 'hod',
          action: 'approve',
          timestamp: now - 86400000 * 28,
        },
        {
          step: 'so_1',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'so',
          action: 'approve',
          timestamp: now - 86400000 * 25,
        },
        {
          step: 'po_1',
          userId: 'po1',
          userName: 'Mrs. Lakshmi Iyer',
          userRole: 'po',
          action: 'approve',
          timestamp: now - 86400000 * 22,
        },
        {
          step: 'principal_1',
          userId: 'principal1',
          userName: 'Dr. Meera Iyer',
          userRole: 'principal',
          action: 'approve',
          timestamp: now - 86400000 * 19,
        },
        {
          step: 'payment_officer',
          userId: 'pay1',
          userName: 'Mr. Finance Officer',
          userRole: 'payment_officer',
          action: 'approve',
          timestamp: now - 86400000 * 16,
        },
        {
          step: 'so_2',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'so',
          action: 'approve',
          timestamp: now - 86400000 * 13,
        },
        {
          step: 'hod_2',
          userId: 'hod3',
          userName: 'Dr. Sports HOD',
          userRole: 'hod',
          action: 'approve',
          timestamp: now - 86400000 * 10,
        },
        {
          step: 'so_3',
          userId: 'so1',
          userName: 'Mr. Ramesh Verma',
          userRole: 'so',
          action: 'approve',
          timestamp: now - 86400000 * 7,
        },
        {
          step: 'po_2',
          userId: 'po1',
          userName: 'Mrs. Lakshmi Iyer',
          userRole: 'po',
          action: 'approve',
          timestamp: now - 86400000 * 4,
        },
        {
          step: 'principal_2',
          userId: 'principal1',
          userName: 'Dr. Meera Iyer',
          userRole: 'principal',
          action: 'approve',
          timestamp: now - 86400000 * 2,
        },
        {
          step: 'ao',
          userId: 'ao1',
          userName: 'CA. Accountant',
          userRole: 'ao',
          action: 'approve',
          timestamp: now - 86400000 * 1,
        },
      ],
    },
  ];
};
